name: Crypto Scanner

on:
  workflow_dispatch:
  schedule:
    - cron: "7,22,37,52 * * * *"

jobs:
  scan:
    runs-on: ubuntu-latest

    steps:
      - name: Get repository
        uses: actions/checkout@v6

      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: "3.12"

      - name: Run scanner
        run: python scanner.py
